import React, { useEffect, useState } from "react"
import ComboBox from "./ComboBox";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { getBaseUrl } from "../getBaseUrl";





const members = [
    {
      id: 1,
      name: 'Ronald',
      addres: 'Masindi'
    },
    {
      id: 2,
      name: 'James',
      addres: 'Hoima'
    },
    {
      id: 3,
      name: 'Paul',
      addres: 'Kampala'
    }
  ]


  const Home = () => {

    const navigate = useNavigate()

    const [cars, setCars] = useState([]);
    const [error, setError] = useState(null);
    const [loading, setLoading] = useState(false);
    const [fruits, setFruits] = useState([])

   
      const headingStyle = {color: 'Blue', fontSize: '20px'}
   

  //const get cars generated by the server not from the db
  const fetchCars = async() => {
    try {
      const response = await axios.get(getBaseUrl()+'/cars')
      if(response) {
        console.log('cars data', response.data)
        setCars(response.data)
      }
    } catch (error) {
      console.log('an error occured while fetching car data', error);
      setError('An error occurred while fetching car data')
    }
  }

  //get fruits from the database
  const fetchFruits = async() => {
    try {
      const response = await axios.get(getBaseUrl()+'/fruits')
      if(response) {
        console.log('fruits data', response.data)
        setFruits(response.data.fruits)
      }
    } catch (error) {
      console.log('an error occured while fetching fruits data', error);
      setError('An error occurred while fetching fruits data')
    }
  }
/*
  const fetchAll = async() => {
    try {
      setLoading(true)

      await fetchCars();
      await fetchFruits();

    } catch (error) {
      console.log('ERROR Loading initial data: ', error);
      setError('Error loading data')
    }finally{
      setLoading(false)
    }
  }
  */

  useEffect(() => {
    fetchCars();
  }, [])

    return (
      <div>{
      loading ? <div>Loading ...</div> : error ? <div>An error occured while fetching cars</div>:
        <div>
          <div>HOME PAGE</div>

          <div style={{margin: '30px'}}>
            <div style={headingStyle}>Members stored in react itself</div>
            <div>
              {members.map((member, index) => {
                return(<div key={index}>{member.name}</div>)
              })}
            </div>
          </div>


          <div style={{margin: '30px'}}>
            <div style={headingStyle}>Cars generated by the server</div>
            <div>
              {cars.length>0 && cars.map((car, index) => {
                return(<div key={index}>{car?.name}</div>)
              })}
            </div>
          </div>


          <div style={{margin: '30px'}}>
            <div style={headingStyle}>Fruits retrieved from mysql database</div>
            <div>
              {fruits.length>0 && fruits.map((fruit, index) => {
                return(<div key={index}>{fruit?.name}</div>)
              })}
            </div>
          </div>

          <div><button onClick={() => navigate('/about')}>About us</button></div>
        </div>

      }</div>

      )
    
  };

  export default Home;

