import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { getBaseUrl } from "../getBaseUrl";

const members = [
  { id: 1, name: 'Ronald', addres: 'Masindi' },
  { id: 2, name: 'James', addres: 'Hoima' },
  { id: 3, name: 'Paul', addres: 'Kampala' },
  { id: 4, name: 'Newton', addres: 'Nairobi' }
];

const Home = () => {
  const navigate = useNavigate();
  const [cars, setCars] = useState([]);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(false);
  const [fruits, setFruits] = useState([]);

  const headingStyle = { color: 'Blue', fontSize: '20px' };

  const fetchCars = async () => {
    setLoading(true);
    try {
      const response = await axios.get(getBaseUrl() + '/cars');
      if (response) {
        console.log('cars data', response.data);
        setCars(response.data);
      }
    } catch (error) {
      console.log('an error occurred while fetching car data', error);
      setError('An error occurred while fetching car data');
    } finally {
      setLoading(false);
    }
  };

  const fetchFruits = async () => {
    setLoading(true);
    try {
      const response = await axios.get(getBaseUrl() + '/fruits');
      if (response) {
        console.log('fruits data', response.data);
        setFruits(response.data.fruits);
      }
    } catch (error) {
      console.log('an error occurred while fetching fruits data', error);
      setError('An error occurred while fetching fruits data');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCars();
    fetchFruits();
  }, []);

  return (
    <div>
      {loading ? (
        <div>Loading ...</div>
      ) : error ? (
        <div style={{ color: 'red' }}>{error}</div>
      ) : (
        <div>
          <div>HOME PAGE</div>

          <div style={{ margin: '30px' }}>
            <div style={headingStyle}>Members stored in react itself</div>
            <div>
              {members.map((member, index) => (
                <div key={index}>{member.name}</div>
              ))}
            </div>
          </div>

          <div style={{ margin: '30px' }}>
            <div style={headingStyle}>Cars generated by the server</div>
            <div>
              {cars.length > 0 ? (
                cars.map((car, index) => <div key={index}>{car?.name}</div>)
              ) : (
                <div>No cars available</div>
              )}
            </div>
          </div>

          <div style={{ margin: '30px' }}>
            <div style={headingStyle}>Fruits retrieved from mysql database</div>
            <div>
              {fruits.length > 0 ? (
                fruits.map((fruit, index) => <div key={index}>{fruit?.name}</div>)
              ) : (
                <div>No fruits available</div>
              )}
            </div>
          </div>

          <div>
            <button onClick={() => navigate('/about')}>About us</button>
          </div>
        </div>
      )}
    </div>
  );
};

export default Home;
